const initialConferences = {
    "-KAcz5byzQYAKLpQDoPg" : {
      "city" : "London",
      "country" : "UK",
      "description" : "NDC take pride in doing things differently and aims to deliver the ultimate experience for developers. With 7 parallel track, workshops before and during the conference, high quality seminars of some of the software industry`s best key speakers, food served all day, live music during the evening, and live radio show from .NET Rocks!, it is so much more than just a conference. We like to call it a festival for developers. It is a festival because it celebrates developers, the industry and those who endeavour to become masters of their specific area. \n\nNDC London\n\nIn December 2013 NDC did the first NDC London conference. The conference was a huge success and we are happy to announce that the 3rd NDC London is set to happen the week of 11-15 January 2016.\n\nNDC London 2016 is a full week event with Pre-Conference Workshops on 11-12 January and the actual conference on 13-15 January. The workshops are held at De Vere Venues in Canary Wharf while the conference is held at ICC London at ExCeL.",
      "end" : "2016-01-15",
      "start" : "2016-01-13",
      "title" : "NDC London",
      "url" : "http://ndc-london.com/",
      "venue" : "ICC Suites at London ExCeL",
      "verified" : true
    },
    "-KAfURZR5byYI5JvzBKo" : {
      "city" : "Atlanta, GA",
      "country" : "USA",
      "description" : "Discover how the industry's best minds use the latest technologies to build solutions.\n\nData + Integration Java/JavaEE/Spring HTML5 + Javascript Alternative Languages Cloud Agile + Tools Mobile",
      "end" : "2016-02-17",
      "start" : "2016-02-16",
      "title" : "Devnexus",
      "url" : "http://www.devnexus.com/s/index",
      "venue" : "Georgia World Congress Center",
      "verified" : true
    },
    "-KAcx6mW7n_v1dKBBX3Z" : {
      "city" : "Krakow",
      "country" : "Poland",
      "description" : "Lambda Days is an event like no other gathering people passionate about functional programming.\n\nThe first year was an amazing surprise - an explosion of inspiration and positive energy generated by local communities of tech experts, students, specialists, leaders and innovators. Second edition of our conference exceeded all expectations - with almost 400 attendees, 47 speakers and 7 tracks over two days it was hard to decide which opportunity deserves most attention.\n\nWe’ve worked hard, did our homework and hope to keep up the lucky streak. Third time's the charm - do you think we can make it the best one ever?",
      "end" : "2016-02-19",
      "start" : "2016-02-18",
      "title" : "Lambda Days 2016",
      "url" : "http://www.lambdadays.org/",
      "venue" : "AUDITORIUM  MAXIMUM UJ",
      "verified" : true
    },
    "-KAkIMlayAsAfurNoTOM" : {
      "city" : "Sofia",
      "country" : "Bulgaria",
      "description" : "An event about (almost) everything a modern web person should know.\nBulgaria Web Summit is an annual conference about the modern web.\n\nBenefit: Practical lessons which you can immediately apply in your work and thus gain time and money. The attendance fee is actually an investment. An investment in yourselves.\n\nCommunity: A balanced mixture of participants and speakers working in programming, design, marketing and business development. Find partners, colleagues or ideas to develop.\n\nParty! In addition to the event we are planning a great party and other surprises for you. You should treat yourselves to an amazing weekend in Sofia!",
      "end" : "2016-02-20",
      "start" : "2016-02-20",
      "title" : "Bulgaria Web Summit 2016",
      "url" : "http://bulgariawebsummit.com/",
      "venue" : "Inter Expo Center",
      "verified" : true
    },
    "-KAacOXnIfjMT7dFyw8-" : {
      "city" : "SAN FRANCISCO",
      "country" : "USA",
      "description" : "At React.js Conference 2015, we announced React Native, GraphQL, and Relay, and the community response blew us away.\n\nReact opens a world of new possibilities such as server-side rendering, real-time updates, different rendering targets like svg, canvas, iOS, and Android.\n\nWe need to rethink how we write applications using one-way data flow, immutable data structures, the full power of JavaScript and languages targeting it.\n\nJoin us at React.js Conf to shape the future of client-side applications!",
      "end" : "2016-02-23",
      "start" : "2016-02-22",
      "title" : "React.js Conf",
      "url" : "http://conf.reactjs.com/",
      "venue" : "Grant Hyatt hotel",
      "verified" : true
    },
    "-KBbT54CmtsB7eEJ6vUJ" : {
      "city" : "NORWICH",
      "country" : "UK",
      "description" : "Brought to us by Naked Element Ltd., the Norfolk Developers' tech, business and agile conference is going to be even bigger than the three before it.\n\nWith some of our guest speakers already booked and new ideas to make the conference even better, next year’s winter conference is set to be very special.",
      "end" : "2016-02-27",
      "start" : "2016-02-25",
      "title" : "NORDEVCON",
      "url" : "http://www.nordevcon.com/",
      "venue" : "The King’s Centre",
      "verified" : false
    },
    "-KAfUmQh-cr4g7M7mN2J" : {
      "city" : "London",
      "country" : "UK",
      "description" : "EnhanceConf is a one day, single track conference covering the state of the art in progressive enhancement. We will look at the tools and techniques that allow you to extend the reach of your website/application without incurring additional costs.",
      "end" : "2016-03-04",
      "start" : "2016-03-04",
      "title" : "EnhanceConf",
      "url" : "http://enhanceconf.com/index.html",
      "venue" : "Great Room at RSA House",
      "verified" : true
    },
    "K93hNf5i8A33FSDwjZ8" : {
      "city" : "London",
      "country" : "UK",
      "description" : "A practitioner-driven conference, QCon is designed for technical team leads, architects, engineering directors, and project managers who influence innovation in their teams.",
      "end" : "2016-03-09",
      "start" : "2016-03-07",
      "title" : "QCon London",
      "url" : "http://qconlondon.com/",
      "venue" : "The Queen Elizabeth II Conference Centre",
      "verified" : true
    },
    "-KAfVYtdjslwOj2I3fIG" : {
      "city" : "Gøteborg",
      "country" : "Sweden",
      "description" : "A Java developers conference about Java SE, Java EE, Java Open Source Frameworks and technologies, Front-end (Web & Mobile), Cloud & Microservices, IoT, Big Data, Test, Trends & Future, Software Solutions, Case Studies, Real World Experiences, Methodologies & Tools, and other related subjects. ",
      "end" : "2016-03-09",
      "start" : "2016-03-08",
      "title" : "jDays 2016 Gøteborg",
      "url" : "http://www.jdays.se/",
      "venue" : "Clarion Hotel Post",
      "verified" : true
    },
    "K93hGKCh61z1aga34y6" : {
      "city" : "San Fransisco",
      "country" : "USA",
      "description" : "Practical training in JavaScript, HTML5, CSS, and the latest web development technologies and frameworks",
      "end" : "2016-03-10",
      "start" : "2016-03-08",
      "title" : "Fluent",
      "url" : "http://conferences.oreilly.com/fluent/javascript-html-us",
      "venue" : "San Francisco Marriott Marquis",
      "verified" : true
    }  
} 

export default initialConferences;