export const LOADING_CONFERENCES = 'LOADING_CONFERENCES';
export const CONFERENCES_LOADED = 'CONFERENCES_LOADED';
export const ADDING_CONFERENCE = 'ADDING_CONFERENCE';
export const CONFERENCES_ADDED = 'CONFERENCES_ADDED';
export const ADD_CONFERENCE_DIALOG = 'ADD_CONFERENCE_DIALOG';
export const ADD_CONFERENCE_DIALOG_FIELD_CHANGED = 'ADD_CONFERENCE_DIALOG_FIELD_CHANGED';
export const LOGGED_IN = 'LOGGED_IN';
